name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
    - name: Install dependencies
      run: yarn
      working-directory: ./src
    - name: Lint
      run: yarn lint
    - name: Typecheck
      run: yarn lint
    - name: Unit Tests
      run: yarn test
    - name: Coverage
      run: yarn test --coverage
